'use client';
import Link from 'next/link';
import { motion, AnimatePresence } from 'framer-motion';
import { useState } from 'react';
import { ChevronDown, ExternalLink, Github } from 'lucide-react';
import { iconMap, portfolio, type Project } from '@/config/portfolio.config';
import { Button } from './ui/button';
import { ProgressRing, XPBar } from './progress';
import { cn } from '@/lib/utils';

export function LevelHero(){return <section className="grid gap-5 md:grid-cols-[1.2fr_.8fr]"><motion.div initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} className="rounded-3xl border border-line bg-gradient-to-b from-card to-surface p-6 md:p-8"><p className="text-sm text-success">● {portfolio.availability}</p><h1 className="mt-5 text-4xl font-semibold tracking-[-.04em] md:text-6xl">{portfolio.name}</h1><p className="mt-3 text-xl text-secondary">{portfolio.role}</p><p className="mt-6 max-w-2xl leading-7 text-secondary">{portfolio.bio}</p><div className="mt-8"><p className="mb-3 text-sm font-medium">Level {String(portfolio.currentLevel).padStart(2,'0')} — {portfolio.levelTitle}</p><XPBar {...portfolio.xp}/></div></motion.div><div className="rounded-3xl border border-line bg-card p-6"><div className="flex items-center justify-between"><span className="text-sm text-muted">Recruiter snapshot</span><span className="rounded-full bg-accent/15 px-3 py-1 text-xs text-accent">Level aktif</span></div><div className="mt-8 grid place-items-center"><ProgressRing value={82}/></div><p className="mt-6 text-center text-sm leading-6 text-secondary">Interface specialist yang kuat di dashboard, design system, dan performa. Lokasi: {portfolio.location}.</p><Button asChild className="mt-6 w-full"><Link href="/resume">Lihat ringkasan formal</Link></Button></div></section>}
export function CareerMap(){return <section id="map" className="mt-14"><h2 className="text-2xl font-semibold">Career map</h2><div className="mt-6 grid gap-4 md:grid-cols-4">{portfolio.milestones.map((m,i)=>{const Icon=iconMap[m.icon as keyof typeof iconMap];return <motion.article initial={{opacity:0,y:10}} whileInView={{opacity:1,y:0}} transition={{delay:i*.06}} viewport={{once:true}} key={m.title} className="relative rounded-2xl border border-line bg-card p-5"><Icon className="text-accent" size={20}/><p className="mt-5 text-sm text-muted">{m.year}</p><h3 className="mt-1 font-medium">{m.title}</h3><p className="mt-3 text-sm leading-6 text-secondary">{m.description}</p></motion.article>})}</div></section>}
export function SkillTree(){const [open,setOpen]=useState(portfolio.skills[0].name);return <section id="skills" className="mt-14"><h2 className="text-2xl font-semibold">Skill tree</h2><div className="mt-6 space-y-3">{portfolio.skills.map(cat=><div key={cat.name} className="rounded-2xl border border-line bg-card"><button onClick={()=>setOpen(open===cat.name?'':cat.name)} className="focus-ring flex w-full items-center justify-between p-5 text-left"><span><b>{cat.name}</b><p className="mt-1 text-sm text-secondary">{cat.summary}</p></span><ChevronDown className={cn('transition',open===cat.name&&'rotate-180')}/></button><AnimatePresence>{open===cat.name&&<motion.div initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}} className="overflow-hidden"><div className="grid gap-3 border-t border-line p-5 md:grid-cols-3">{cat.skills.map(s=><div key={s.name} className="rounded-xl bg-white/[.03] p-4"><div className="flex items-center justify-between gap-3"><h3 className="font-medium">{s.name}</h3><span className="text-xs text-cyan">{s.level}</span></div><p className="mt-2 text-sm leading-6 text-secondary">{s.description}</p><div className="mt-4 h-1.5 rounded-full bg-white/10"><div className="h-full rounded-full bg-success" style={{width:`${s.progress}%`}}/></div></div>)}</div></motion.div>}</AnimatePresence></div>)}</div></section>}
export function ProjectUnlockCard({project}:{project:Project}){return <motion.article whileHover={{y:-4}} className="min-w-[82vw] rounded-3xl border border-line bg-card p-5 md:min-w-0"><div className="flex items-center justify-between"><span className="rounded-full bg-success/10 px-3 py-1 text-xs text-success">{project.status}</span><span className="text-xs text-muted">{project.difficulty}</span></div><h3 className="mt-5 text-xl font-semibold">{project.title}</h3><p className="mt-3 text-sm leading-6 text-secondary">{project.problem}</p><p className="mt-4 rounded-xl bg-white/[.03] p-3 text-sm text-primary">{project.impact}</p><div className="mt-4 flex flex-wrap gap-2">{project.stack.map(s=><span key={s} className="rounded-lg border border-line px-2 py-1 text-xs text-secondary">{s}</span>)}</div><div className="mt-5 flex gap-2"><Button asChild><Link href={`/projects/${project.slug}`}>Buka case study</Link></Button><Button asChild variant="ghost"><a href={project.githubUrl} target="_blank"><Github size={16}/></a></Button></div></motion.article>}
export function ProjectsSection(){return <section className="mt-14"><div className="flex items-end justify-between"><h2 className="text-2xl font-semibold">Project unlocks</h2><Link href="/projects" className="text-sm text-cyan">Lihat semua</Link></div><div className="no-scrollbar mt-6 flex gap-4 overflow-x-auto md:grid md:grid-cols-2">{portfolio.projects.slice(0,4).map(p=><ProjectUnlockCard key={p.slug} project={p}/>)}</div></section>}
export function Achievements(){return <section className="mt-14"><h2 className="text-2xl font-semibold">Achievement badges</h2><div className="mt-6 grid gap-4 md:grid-cols-4">{portfolio.achievements.map(a=>{const Icon=iconMap[a.icon as keyof typeof iconMap];return <div key={a.title} className="rounded-2xl border border-line bg-card p-5"><Icon className="text-cyan" size={20}/><h3 className="mt-4 font-medium">{a.title}</h3><p className="mt-2 text-sm leading-6 text-secondary">{a.description}</p></div>})}</div></section>}
export function RecruiterMode(){const [on,setOn]=useState(false);return <section className="mt-14 rounded-3xl border border-line bg-elevated p-6"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><h2 className="text-2xl font-semibold">Recruiter mode</h2><p className="mt-2 text-secondary">Ubah halaman menjadi ringkasan cepat untuk proses hiring.</p></div><Button variant={on?'primary':'outline'} onClick={()=>setOn(!on)}>{on?'Mode aktif':'Aktifkan'}</Button></div><AnimatePresence>{on&&<motion.div initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:8}} className="mt-6 grid gap-4 md:grid-cols-3"><p className="rounded-2xl bg-background/60 p-5 leading-7 text-secondary md:col-span-2">{portfolio.recruiter.summary}</p><div className="rounded-2xl bg-background/60 p-5"><h3 className="font-medium">Skill terkuat</h3><ul className="mt-3 space-y-2 text-sm text-secondary">{portfolio.recruiter.strongestSkills.map(s=><li key={s}>• {s}</li>)}</ul></div></motion.div>}</AnimatePresence></section>}
export function ContactCTA(){return <section className="mt-14 rounded-3xl border border-line bg-gradient-to-br from-card to-elevated p-6 md:p-8"><h2 className="text-2xl font-semibold">Punya interface yang mulai terasa berat?</h2><p className="mt-3 max-w-2xl leading-7 text-secondary">Kirim konteks singkat: produknya apa, bagian mana yang paling menghambat, dan target waktunya. Saya akan balas dengan pertanyaan yang langsung mengarah ke keputusan.</p><div className="mt-6 flex flex-wrap gap-3"><Button asChild><a href={`mailto:${portfolio.email}`}>Email {portfolio.name}</a></Button>{portfolio.socials.map(s=><Button key={s.label} asChild variant="outline"><a href={s.href} target={s.href.startsWith('http')?'_blank':undefined}>{s.label}<ExternalLink size={14}/></a></Button>)}</div></section>}
